database:
  type: mongodb
  host: mongodb
  port: 5432
  user: root
  password: rootpassword
  dbname: backup_test

backup:
  path: /backup/
  retention_days: 7

cloud:
  aws:
    enabled: false

  gcp:
    enabled: false

notifications:
  slack:
    enabled: false